# Generated by Django 5.1.3 on 2024-12-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_log',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='email_log',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email_log',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
